[project]
name = "aoc2025"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.3.251201",
    "pathlib>=1.0.1",
    "pydantic>=2.12.5",
]
